jupyter notebook theme


In [10]:
#!jt -t gruvboxd 
!jt -r

Reset css and font defaults in:
C:\Users\tlsck\.jupyter\custom &
C:\Users\tlsck\AppData\Roaming\jupyter\nbextensions


In [1]:
!jt -t grade3 -tf merriserif -tfs 22 -nf ptsans -nfs 14 -ofs 13

Raw Wave Signal by speech book -signal에 있는 정수값들은 뭘까?

In [2]:
import scipy.io.wavfile
sample_rate, signal = scipy.io.wavfile.read('../Data/example.wav')

In [3]:
sample_rate

16000

In [4]:
signal

array([36, 37, 60, ...,  7,  9,  8], dtype=int16)

In [5]:
len(signal)

183280

In [6]:
len(signal)/ sample_rate

11.455

In [7]:
signal = signal[0:int(3.5 * sample_rate)]

In [8]:
len(signal)

56000

Preemphasis -고주파 성분 Power up!

In [9]:
import numpy as np
pre_emphasis = 0.97
emphasized_signal = np.append(signal[0], signal[1:] - pre_emphasis * signal[:-1])

In [10]:
emphasized_signal

array([  36.  ,    2.08,   24.11, ..., -233.76, -262.5 ,  -61.87])

Framing

In [11]:
frame_size = 0.025
frame_stride = 0.01
frame_length, frame_step = frame_size * sample_rate, frame_stride * sample_rate
signal_length = len(emphasized_signal)
frame_length = int(round(frame_length))
frame_step = int(round(frame_step))
num_frames = int(np.ceil(float(np.abs(signal_length - frame_length)) / frame_step))
pad_signal_length = num_frames * frame_step + frame_length
z = np.zeros((pad_signal_length - signal_length))
pad_signal = np.append(emphasized_signal, z)
indices = np.tile(np.arange(0, frame_length), (num_frames, 1)) + \
          np.tile(np.arange(0, num_frames * frame_step, frame_step), (frame_length, 1)).T
frames = pad_signal[indices.astype(np.int32, copy=False)]

In [12]:
pad_signal

array([36.  ,  2.08, 24.11, ...,  0.  ,  0.  ,  0.  ])

In [13]:
len(pad_signal)

56080

In [14]:
indices

array([[    0,     1,     2, ...,   397,   398,   399],
       [  160,   161,   162, ...,   557,   558,   559],
       [  320,   321,   322, ...,   717,   718,   719],
       ...,
       [55200, 55201, 55202, ..., 55597, 55598, 55599],
       [55360, 55361, 55362, ..., 55757, 55758, 55759],
       [55520, 55521, 55522, ..., 55917, 55918, 55919]])

In [15]:
indices.shape

(348, 400)

In [16]:
frames

array([[  36.  ,    2.08,   24.11, ...,    4.56,    3.74,    2.89],
       [  16.43,  -32.15,  -47.2 , ...,  -13.06,  -16.45,    2.07],
       [  -9.  ,   -9.27,   11.46, ...,   -5.09,   -7.24,   -2.45],
       ...,
       [ 315.7 ,  130.65,  211.81, ..., -121.15,  -17.69, -195.02],
       [ 283.62, 1098.42,  815.34, ...,   20.53,  136.92,  150.79],
       [ -59.03, -212.81, -289.18, ..., -157.35,  -81.12,   24.54]])

In [17]:
frames *= np.array([0.54 - 0.46 * np.cos((2 * np.pi * n) / (frame_length - 1)) for n in range(frame_length)])

In [18]:
frames

array([[  2.88      ,   0.16651863,   1.9343    , ...,   0.36584023,
          0.29941331,   0.2312    ],
       [  1.3144    ,  -2.57383364,  -3.78676733, ...,  -1.04777926,
         -1.31693821,   0.1656    ],
       [ -0.72      ,  -0.7421287 ,   0.91941427, ...,  -0.40836114,
         -0.57961293,  -0.196     ],
       ...,
       [ 25.256     ,  10.45945147,  16.99311838, ...,  -9.7196369 ,
         -1.41620893, -15.6016    ],
       [ 22.6896    ,  87.93624714,  65.41319644, ...,   1.64708333,
         10.96140908,  12.0632    ],
       [ -4.7224    , -17.03693738, -23.20036812, ..., -12.62389489,
         -6.49422659,   1.9632    ]])

In [22]:
len(frames)

348

In [23]:
NFFT = 512
dft_frames = np.fft.rfft(frames, NFFT)

In [25]:
 np.fft.rfft([0.2, 0.7, 0.5, 0.3, 0.1])

array([ 1.8+0.j        , -0.2-0.68819096j, -0.2-0.16245985j])

In [27]:
!pip install torchaudio

ERROR: Could not find a version that satisfies the requirement torchaudio (from versions: none)
ERROR: No matching distribution found for torchaudio
