In [2]:
import UrbanSound8k_features as F
import numpy as np

In [3]:
parent_dir="C:\\Users\\tlsck\\IMPRESS\\Data\\UrbanSound8K\\audio"
tr_sub_dirs=['fold1','fold2']
ts_sub_dirs=['fold3']
tr_features,tr_labels=F.parse_audio_files(parent_dir,tr_sub_dirs)
ts_features,ts_labels=F.parse_audio_files(parent_dir,ts_sub_dirs)

tr_labels=F.one_hot_encode(tr_labels)
ts_labels=F.one_hot_encode(ts_labels)


C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\101415-3-0-2.wav
[-0.00011783 -0.00017157 -0.00017749 ... -0.04598654 -0.04624664
 -0.05089863] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\101415-3-0-3.wav
[-0.00060348 -0.00104231 -0.00083736 ... -0.00025618 -0.00023532
 -0.00033718] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\101415-3-0-8.wav
[ 0.23950581  0.35340017  0.29654667 ... -0.00287635 -0.00120912
 -0.0011842 ] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\102106-3-0-0.wav
[ 0.00672329  0.00222221 -0.00137667 ...  0.0011014  -0.00193948
  0.00286356] 22050



C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=566
  n_fft, y.shape[-1]


C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\102305-6-0-0.wav
[-9.001046e-06  5.259104e-04  9.959461e-04 ...  0.000000e+00  0.000000e+00
  0.000000e+00] 22050



C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=900
  n_fft, y.shape[-1]


C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\102842-3-0-1.wav
[ 0.00680424  0.01001977  0.00837677 ... -0.00625793 -0.00586295
 -0.0068677 ] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\102842-3-1-0.wav
[ 0.0073953   0.00981416  0.00828659 ... -0.00841427 -0.00809684
 -0.01073948] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\102842-3-1-5.wav
[-0.00522718 -0.00692255 -0.00609466 ...  0.0034847   0.00220837
  0.00103147] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\102842-3-1-6.wav
[-0.00760933 -0.00997894 -0.00855114 ... -0.00775176 -0.00707063
 -0.0061991 ] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-0-0.wav
[0.00176006 0.00509129 0.00622216 ... 0.02590852 0.02770032 0.02473842] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-0-1.wav
[-0.0188013   0.00157722  0.03567883 ... -0.00393829 -0.00735717
  0.00411026] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-0-2.wav
[

C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=951
  n_fft, y.shape[-1]
C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=476
  n_fft, y.shape[-1]


C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-3-0.wav
[-0.00625723 -0.00717413  0.00481367 ...  0.0343676   0.03915804
  0.03914637] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-3-1.wav
[ 0.01871075  0.02376172  0.0153701  ... -0.01513544 -0.03028706
 -0.06111132] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-3-2.wav
[0.021896   0.02605435 0.02578595 ... 0.01458437 0.00677887 0.01316097] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-3-3.wav
[-0.03542176 -0.0409974  -0.03439824 ...  0.04704179  0.04038464
  0.04063282] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-4-0.wav
[-0.00349573 -0.02283456 -0.03126134 ...  0.00996819  0.02522952
  0.04880725] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-4-1.wav
[ 0.01872071  0.01442721  0.01095289 ... -0.00559834  0.0005944
  0.01093882] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\103074-7-4-2.wav
[ 

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\108362-2-0-23.wav
[-0.00705442 -0.00085154  0.04417101 ...  0.04327278  0.04919447
  0.04552462] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\108362-2-0-29.wav
[0.01089714 0.01537469 0.01423633 ... 0.02319393 0.01749626 0.01280705] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\108362-2-0-30.wav
[0.05716978 0.07931302 0.06644955 ... 0.0282666  0.03222017 0.03999514] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\108362-2-0-7.wav
[-0.03072898 -0.03394879 -0.01849157 ... -0.03957968 -0.0775051
 -0.07465047] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\108362-2-0-9.wav
[-0.02427351 -0.01168059  0.0049942  ...  0.06953245  0.10962363
  0.14663236] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\113205-5-0-0.wav
[-0.0149221  -0.02940309 -0.02938617 ...  0.07003167  0.06842733
  0.07696408] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\113205-5-1-0.wav
[-0.09

C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=716
  n_fft, y.shape[-1]
C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=358
  n_fft, y.shape[-1]
C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=179
  n_fft, y.shape[-1]


[-0.00653855 -0.0149445  -0.00980665 ... -0.00206805  0.03231079
  0.0086829 ] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\119455-5-0-1.wav
[-0.01077605 -0.01464386 -0.02743492 ... -0.01416698  0.00096342
 -0.01334951] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\119455-5-0-2.wav
[ 0.01261052  0.00539923  0.01276019 ... -0.01722801 -0.02455092
 -0.03031666] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\119455-5-0-3.wav
[ 0.01195724  0.01163625 -0.01745503 ...  0.02250949  0.01682553
  0.0398191 ] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\119455-5-0-4.wav
[-0.03869144 -0.04663915 -0.02298754 ...  0.02464953  0.01266694
 -0.00205391] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\119455-5-0-5.wav
[ 0.02547013  0.02337238  0.01251269 ... -0.02670293 -0.02368032
 -0.01150481] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\119455-5-0-6.wav
[-0.00890414 -0.02006797 -0.04516643 ...  0.02241636  0.05104525

C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=703
  n_fft, y.shape[-1]


C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\130030-3-0-0.wav
[ 0.00045524 -0.00462464 -0.00803517 ... -0.00025589 -0.00026846
  0.        ] 22050



C:\Users\tlsck\Anaconda3\envs\study\lib\site-packages\librosa\core\spectrum.py:224: UserWarning: n_fft=1024 is too small for input signal of length=893
  n_fft, y.shape[-1]


C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\132016-9-0-0.wav
[ 0.00496799  0.00714737  0.00604998 ... -0.05777008 -0.06739052
 -0.08308025] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\132016-9-0-11.wav
[-0.01497578 -0.02787026 -0.03131371 ...  0.01675158  0.01505808
  0.01393163] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\132016-9-0-14.wav
[-0.05270794 -0.07500614 -0.06084945 ... -0.02892835 -0.0291627
 -0.03135211] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\132016-9-0-16.wav
[-0.02782093 -0.0432311  -0.02890611 ...  0.02032206  0.02364764
  0.00984563] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\132016-9-0-20.wav
[-0.02632897 -0.03706704 -0.02826045 ...  0.09138536  0.09795
  0.10743127] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\132016-9-0-6.wav
[-0.0784167  -0.11046977 -0.08385179 ... -0.00587536  0.00208548
  0.01870338] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\134717-0-0-

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\138031-2-0-45.wav
[-0.00063588 -0.00095412 -0.0007934  ... -0.00062381 -0.00064148
 -0.000752  ] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\138031-2-0-47.wav
[-0.0005756  -0.00091348 -0.00083901 ... -0.0001255  -0.0001182
 -0.00012987] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\138031-2-0-7.wav
[-0.00041055 -0.0006545  -0.00057793 ... -0.00031698 -0.0003353
 -0.00039707] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\139951-9-0-13.wav
[ 0.00885764  0.00710963  0.0010063  ...  0.00956463  0.00525591
 -0.00275651] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\139951-9-0-17.wav
[ 0.01737515  0.01552379  0.00404832 ...  0.03613062  0.00948416
 -0.03331032] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\139951-9-0-29.wav
[-0.00708063 -0.01140668 -0.01302548 ...  0.00936298  0.00741908
  0.00447359] 22050

C:\Users\tlsck\IMPRESS\Data\UrbanSound8K\audio\fold1\139951-9

KeyboardInterrupt: 